name: Infra Deployment

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy Infra
    runs-on: self-hosted
    env:
      ANSIBLE_CONFIG: ansible/ansible.cfg
      ANSIBLE_INVENTORY: /opt/ci_cd_configs/ansible/inventories/production/hosts.yml

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: List files in repository
        run: |
          echo "Current directory:"
          pwd
          echo "Files in the repository:"
          ls -la

      - name: Debug current working directory
        run: |
            pwd
            cat ansible/ansible.cfg
            ansible-inventory --list

      - name: Run Ansible playbook
        run: |
          ansible-playbook ansible/playbooks/echo_hostname.yml
            ansible-playbook ansible/playbooks/echo_whoami.yml