name: Infra Deployment

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy Infra
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: List files in repository
        run: |
          echo "Current directory:"
          pwd
          echo "Files in the repository:"
          ls -la

      - name: Run Ansible playbook
        run: |
          ansible-playbook ansible/playbooks/echo_hostname.yml