name: Infra Deployment

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy Infra
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3